Univer/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Univer.Models
{
    public class Group
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime Year { get; set; }

        [ForeignKey("Curator")]
        public int? CuratorId { get; set; }
        public Instructor Curator { get; set; }

        public int? CourseId { get; set; }
        [ForeignKey("CourseId")]
        public Course Course { get; set; }
        public int? SpecialId { get; set; }
        [ForeignKey("SpecialId")]
        public Special Special { get; set; }

        public ICollection<Student> Students { get; set; }
    }
}

Univer/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Univer.Data;
using Univer.Models;
using Univer.Service.Courses;

namespace Univer.Controllers
{
    public class CoursesController : Controller
    {
        private ICourseService _courseService;

        public CoursesController(ICourseService courseService)
        {
            _courseService = courseService;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            var courseList = _courseService.List();

            return View(await Task.Run(() => courseList));
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = _courseService.GetById((int) id);

            if (course == null)
            {
                return NotFound();
            }

            return View(await Task.Run(() => course));
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["Groups"] = new SelectList(_courseService.GroupList(), "Id", "Title");
            ViewData["Instructors"] = new SelectList(_courseService.InstructorList(), "Id", "FullName");
            ViewData["Students"] = new SelectList(_courseService.StudentList(), "Id", "FullName");

            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Course course, List<Int32> list, List<Int32> list1, List<Int32> list2)
        {
            if (ModelState.IsValid)
            {
                _courseService.Create(course, list, list1, list2);
                return RedirectToAction(await Task.Run(() => nameof(Index)));
            }

            ViewData["Groups"] = new SelectList(_courseService.GroupList(), "Id", "Title");
            ViewData["Instructors"] = new SelectList(_courseService.InstructorList(), "Id", "FullName");
            ViewData["Students"] = new SelectList(_courseService.StudentList(), "Id", "FullName");

            return View(await Task.Run(() => course));
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = _courseService.GetById((int) id);

            if (course == null)
            {
                return NotFound();
            }

            ViewData["Groups"] = new SelectList(_courseService.GroupList(), "Id", "Title");
            ViewData["Instructors"] = new SelectList(_courseService.InstructorList(), "Id", "FullName");
            ViewData["Students"] = new SelectList(_courseService.StudentList(), "Id", "FullName");

            return View(await Task.Run(() => course));
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Course course, List<Int32> list, List<Int32> list1, List<Int32> list2)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _courseService.Update(id, course, list, list1, list2);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(await Task.Run(() => nameof(Index)));
            }

            ViewData["Groups"] = new SelectList(_courseService.GroupList(), "Id", "Title");
            ViewData["Instructors"] = new SelectList(_courseService.InstructorList(), "Id", "FullName");
            ViewData["Students"] = new SelectList(_courseService.StudentList(), "Id", "FullName");

            return View(await Task.Run(() => course));
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = _courseService.GetById((int) id);

            if (course == null)
            {
                return NotFound();
            }

            return View(await Task.Run(() => course));
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _courseService.Delete(id);
            return RedirectToAction(await Task.Run(() => nameof(Index)));
        }

        private bool CourseExists(int id)
        {
            return _courseService.CourseExists(id);
        }
    }
}

Univer/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Univer.Data;
using Univer.Models;
using Univer.Service.Groups;

namespace Univer.Controllers
{
    public class GroupsController : Controller
    {
        private IGroupService _groupService;

        public GroupsController(IGroupService groupservice)
        {
            _groupService = groupservice;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            var list = _groupService.List();
            return View(await Task.Run(() => list));
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = _groupService.GetById((int) id);

            if (@group == null)
            {
                return NotFound();
            }

            return View(await Task.Run(() => @group));
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            ViewData["Curator"] = new SelectList(_groupService.CuratorList(null), "Id", "FullName");
            ViewData["Course"] = new SelectList(_groupService.CourseList(), "Id", "Title");
            ViewData["Special"] = new SelectList(_groupService.SpecialList(), "Id", "Title");
            ViewData["Students"] = new SelectList(_groupService.StudentList(null), "Id", "FullName");

            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Group @group, List<Int32> list)
        {
            if (ModelState.IsValid)
            {
                _groupService.Create(group, list);
                return RedirectToAction(await Task.Run(() => nameof(Index)));
            }

            ViewData["Course"] = new SelectList(_groupService.CourseList(), "Id", "Title", @group.CourseId);
            ViewData["Curator"] = new SelectList(_groupService.CuratorList(null), "Id", "FullName", @group.CuratorId);
            ViewData["Special"] = new SelectList(_groupService.SpecialList(), "Id", "Title", @group.SpecialId);
            ViewData["Students"] = new SelectList(_groupService.StudentList(null), "Id", "FullName");

            return View(await Task.Run(() => @group));
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = _groupService.GetById((int) id);

            if (@group == null)
            {
                return NotFound();
            }
            ViewData["Course"] = new SelectList(_groupService.CourseList(), "Id", "Title", @group.CourseId);
            ViewData["Curator"] = new SelectList(_groupService.CuratorList((int) id), "Id", "FullName", @group.CuratorId);
            ViewData["Special"] = new SelectList(_groupService.SpecialList(), "Id", "Title", @group.SpecialId);
            ViewData["Students"] = new SelectList(_groupService.StudentList(id), "Id", "FullName");

            return View(await Task.Run(() => @group));
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Group @group, List<Int32> list)
        {
            if (id != @group.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _groupService.Update(id, @group, list);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(await Task.Run(() => nameof(Index)));
            }
            ViewData["Course"] = new SelectList(_groupService.CourseList(), "Id", "Title", @group.CourseId);
            ViewData["Curator"] = new SelectList(_groupService.CuratorList((int) id), "Id", "FullName", @group.CuratorId);
            ViewData["Special"] = new SelectList(_groupService.SpecialList(), "Id", "Title", @group.SpecialId);
            ViewData["Students"] = new SelectList(_groupService.StudentList(id), "Id", "FullName");

            return View(await Task.Run(() => @group));
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = _groupService.GetById((int) id);

            if (@group == null)
            {
                return NotFound();
            }

            return View(await Task.Run(() => @group));
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _groupService.Delete(id);
            return RedirectToAction(await Task.Run(() => nameof(Index)));
        }

        private bool GroupExists(int id)
        {
            return _groupService.GroupExists(id);
        }
    }
}

Univer/Controllers/SpecialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Univer.Data;
using Univer.Models;
using Univer.Service.Specials;

namespace Univer.Controllers
{
    public class SpecialsController : Controller
    {
        private ISpecialService _specialService;

        public SpecialsController(ISpecialService specialService)
        {
            _specialService = specialService;
        }

        // GET: Specials
        public async Task<IActionResult> Index()
        {
            return View(await Task.Run(() => _specialService.List()));
        }

        // GET: Specials/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var special = _specialService.GetById((int) id);

            if (special == null)
            {
                return NotFound();
            }

            return View(await Task.Run(() => special));
        }

        // GET: Specials/Create
        public IActionResult Create()
        {
            ViewData["Groups"] = new SelectList(_specialService.GroupList(), "Id", "Title");

            return View();
        }

        // POST: Specials/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Special special, List<Int32> list)
        {
            if (ModelState.IsValid)
            {
                _specialService.Create(special, list);
                return RedirectToAction(await Task.Run(() => nameof(Index)));
            }

            ViewData["Groups"] = new SelectList(_specialService.GroupList(), "Id", "Title");

            return View(await Task.Run(() => special));
        }

        // GET: Specials/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var special = _specialService.GetById((int) id);

            if (special == null)
            {
                return NotFound();
            }

            ViewData["Groups"] = new SelectList(_specialService.GroupList(), "Id", "Title");

            return View(await Task.Run(() => special));
        }

        // POST: Specials/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Special special, List<Int32> list)
        {
            if (id != special.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _specialService.Update(id, special, list);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpecialExists(special.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(await Task.Run(() => nameof(Index)));
            }

            ViewData["Groups"] = new SelectList(_specialService.GroupList(), "Id", "Title");

            return View(await Task.Run(() => special));
        }

        // GET: Specials/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var special = _specialService.GetById((int) id);

            if (special == null)
            {
                return NotFound();
            }

            return View(await Task.Run(() => special));
        }

        // POST: Specials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _specialService.Delete(id);
            return RedirectToAction(await Task.Run(() => nameof(Index)));
        }

        private bool SpecialExists(int id)
        {
            return _specialService.SpecialExists(id);
        }
    }
}

Univer/Views/Groups/Create.cshtml
@model Univer.Models.Group

@{
    ViewData["Title"] = "Создать";
}

<h1>Создать</h1>

<h4>Группа</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">Группа</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label">Год</label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuratorId" class="control-label">Куратор</label>
                @Html.DropDownListFor(x => x.CuratorId, ViewBag.Curator as SelectList, " ", new { @class = "form-control" })
                <!-- <select asp-for="CuratorId" class="form-control" asp-items="ViewBag.Curator"></select> -->
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label">Курс</label>
                @Html.DropDownListFor(x => x.CourseId, ViewBag.Course as IEnumerable<SelectListItem>, "Выберите значение из списка", new { @class = "form-control" })
                <!-- <select asp-for="CourseId" class="form-control" asp-items="ViewBag.Course"></select> -->
            </div>
            <div class="form-group">
                <label asp-for="SpecialId" class="control-label">Предметы</label>
                <select asp-for="SpecialId" class="form-control" asp-items="ViewBag.Special"></select>
            </div>
            <div class="form-group">
                <label for="list[]" class="control-label">Студенты</label>
                @Html.DropDownList("list[]", ViewBag.Students as SelectList, new { @class = "form-control", multiple=true, size=3, id="list[]" })
                <!-- <select asp-for="CourseId" class="form-control" asp-items="ViewBag.Course"></select> -->
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Univer/Views/Groups/Delete.cshtml
@model Univer.Models.Group

@{
    ViewData["Title"] = "Удалить";
}

<h1>Удалить</h1>

<h3>Вы уверены, что хотите удалить данный объект?</h3>
<div>
    <h4>Группа</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Группа
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            Год
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            Куратор
        </dt>
        <dd class="col-sm-10">
            @if (Model.CuratorId > 0)
            {
                <a asp-controller="Instructors" asp-action="Details" asp-route-id="@Model.Id">@Model.Curator.FullName</a>
            }
        </dd>
        <dt class="col-sm-2">
            Курс
        </dt>
        <dd class="col-sm-10">
            @if (Model.CourseId > 0)
            {
                <a asp-controller="Courses" asp-action="Details" asp-route-id="@Model.CourseId">@Model.Course.Title</a>
            }
        </dd>
        <dt class="col-sm-2">
            Предметы
        </dt>
        <dd class="col-sm-10">
            @if (Model.Special is not null)
            {
            <a asp-controller="Specials" asp-action="Details" asp-route-id="@Model.SpecialId">@Model.Special.Title</a>
            }
        </dd>
        <dt class="col-sm-2">
            Студенты
        </dt>
        <dd class="col-sm-10">
            <ul>
                @foreach (Student s in Model.Students)
                {
                    <li>
                        <a asp-controller="Students" asp-action="Details" asp-route-id="@s.Id">@s.FullName</a>
                    </li>
                }
            </ul>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

Univer/Views/Groups/Details.cshtml
@model Univer.Models.Group

@{
    ViewData["Title"] = "Информация о группе";
}

<h1>Информация о группе</h1>

<div>
    <h4>Группа</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Группа
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            Год
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            Куратор
        </dt>
        <dd class="col-sm-10">
            @if (Model.CuratorId > 0)
            {
                <a asp-controller="Instructors" asp-action="Details" asp-route-id="@Model.Id">@Model.Curator.FullName</a>
            }
        </dd>
        <dt class="col-sm-2">
            Курс
        </dt>
        <dd class="col-sm-10">
            @if (Model.CourseId > 0)
            {
                <a asp-controller="Courses" asp-action="Details" asp-route-id="@Model.CourseId">@Model.Course.Title</a>
            }
        </dd>
        <dt class="col-sm-2">
            Предметы
        </dt>
        <dd class="col-sm-10">
            @if (Model.Special is not null)
            {
            <a asp-controller="Specials" asp-action="Details" asp-route-id="@Model.SpecialId">@Model.Special.Title</a>
            }       
        </dd>
        <dt class="col-sm-2">
            Студенты
        </dt>
        <dd class="col-sm-10">
            <dl>
                @foreach (Student s in Model.Students)
                {
                    <dd>
                        <a asp-controller="Students" asp-action="Details" asp-route-id="@s.Id">@s.FullName</a>
                    </dd>
                }
            </dl>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Изменить</a> |
    <a asp-action="Index">Вернуться к списку</a>
</div>

Univer/Views/Groups/Edit.cshtml
@model Univer.Models.Group

@{
    ViewData["Title"] = "Редактировать";
}

<h1>Редактировать</h1>

<h4>Группа</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label">Группа</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label">Год</label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuratorId" class="control-label">Куратор</label>
                @Html.DropDownListFor(x => x.CuratorId, ViewBag.Curator as SelectList, " ", new { @class = "form-control" })
                <!-- <select asp-for="CuratorId" class="form-control" asp-items="ViewBag.Curator"></select> -->
                <span asp-validation-for="CuratorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label">Курс</label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.Course "></select>
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpecialId" class="control-label">Предметы</label>
                <select asp-for="SpecialId" class="form-control" asp-items="ViewBag.Special"></select>
                <span asp-validation-for="SpecialId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="list[]" class="control-label">Студенты</label>
                @Html.DropDownList("list[]", ViewBag.Students as SelectList, new { @class = "form-control", multiple = true, size = 3, id="list[]" })
                <!-- <select asp-for="CourseId" class="form-control" asp-items="ViewBag.Course"></select> -->
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Univer/Views/Groups/Index.cshtml
@model IEnumerable<Univer.Models.Group>

@{
    ViewData["Title"] = "Группы";
}

<h1>Группы</h1>

<p>
    <a asp-action="Create">Создать</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Группа
            </th>
            <th>
                Год
            </th>
            <th>
                Куратор
            </th>
            <th>
                Курс
            </th>
            <th>
                Предметы
            </th>
            <th>
                Студенты
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @if (item.Curator != null)
                {
                    <a asp-controller="Instructors" asp-action="Details" asp-route-id="@item.CuratorId">@item.Curator.FullName</a>
                }
            </td>
            <td>
                @if (item.Course != null)
                {
                    <a asp-controller="Courses" asp-action="Details" asp-route-id="@item.CourseId">@item.Course.Title</a>
                }
            </td>
            <td>
                @if (item.Special != null)
                {
                    <a asp-controller="Specials" asp-action="Details" asp-route-id="@item.SpecialId">@item.Special.Title</a>
                }
            </td>
            <td>
                <dl>
                    @foreach(Student s in item.Students)
                    {
                    <dd>
                        <a asp-controller="Students" asp-action="Details" asp-route-id="@s.Id">@s.FullName</a>
                    </dd>
                    }
                </dl>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>